name: DuoSpend
options:
  bundleIdPrefix: fr.beabot
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: ""
targets:
  DuoSpend:
    type: application
    platform: iOS
    sources:
      - path: DuoSpend
    resources:
      - path: DuoSpend/Resources/Assets.xcassets
    settings:
      INFOPLIST_GENERATION: YES
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
      DEVELOPMENT_ASSET_PATHS: "\"DuoSpend/Preview Content\""
      SWIFT_STRICT_CONCURRENCY: complete
  DuoSpendTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - DuoSpendTests
    dependencies:
      - target: DuoSpend
    settings:
      INFOPLIST_GENERATION: YES
      GENERATE_INFOPLIST_FILE: YES
